---
version: 2

updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
      time: '22:00'
    ignore:
      - dependency-name: 'org.springframework.boot:spring-boot-starter-parent'
        update-types: [ 'version-update:semver-major' ]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '22:00'
